version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: convo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: convo
    ports:
      - "55432:5432"
    volumes:
      - convo_postgres_data:/var/lib/postgresql/data

volumes:
  convo_postgres_data:
